name: tsperf
channels:
  - defaults
  - r
dependencies:
  - python=3.6
  - numpy=1.15.1
  - pandas=0.23.4
  - xlrd=1.1.0
  - urllib3=1.21.1
  - scikit-learn=0.20.3
  - r=3.5.1
  - r-quantreg
  - r-data.table
  - r-doparallel
